<?php

return [
    'auth' => [
        'session_lifetime_hours' => 8,
        'auth_method' => 'internal',
        'password_min_length' => 12,
        'sso_enabled' => false,
        'hide_internal_prompt' => false,
        'auto_user_provisioning' => false,
        'oauth_auto_team_membership' => false,
        'oauth_provider' => 'custom',
        'oauth_google_enabled' => false,
        'oauth_github_enabled' => false,
        'oauth_custom_enabled' => false,
        'oauth_client_id' => '',
        'oauth_client_secret' => '',
        'oauth_authorization_url' => '',
        'oauth_token_url' => '',
        'oauth_resource_url' => '',
        'oauth_redirect_url' => '',
        'oauth_logout_url' => '',
        'oauth_user_identifier' => 'id',
        'oauth_scopes' => 'openid,email,profile',
        'oauth_auth_style' => 'auto',
        'ldap_enabled' => false,
        'ldap_host' => '',
        'ldap_port' => 389,
        'ldap_anonymous' => false,
        'ldap_bind_dn' => '',
        'ldap_bind_password' => '',
        'ldap_use_starttls' => false,
        'ldap_use_tls' => false,
        'ldap_verify_certificate' => true,
        'ldap_base_dn' => '',
        'ldap_user_filter' => '(objectClass=person)',
        'ldap_username_attribute' => 'uid',
        'ldap_email_attribute' => 'mail',
        'ldap_group_base_dn' => '',
        'ldap_group_filter' => '(objectClass=groupOfNames)',
        'ldap_group_membership_attribute' => 'member',
        'ldap_assign_admin_by_group' => false,
        'ldap_admin_group_names' => '',
        'ldap_fallback_email_domain' => 'ldap.local',
        'login_headline' => 'Ingreso seguro para operacion interna',
        'login_slogan' => 'Acceso administrativo reforzado para operaciones, facturacion y gestion comercial.',
    ],
];
